#!/usr/bin/env bash
#Displays numbers from 1 to 100.
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5

num=1
while [ $num -eq 100 ]
do
    num=$((num+1))
    echo "$num"
    for [ $num%3 = 0 && $num%5 =  0 ]
    do
        echo "FizzBuzz"
        for [ $num%3 = 0 ]
        do
            echo "Fizz"
            for [ $num%5 = 0 ]
            do
                echo "Buzz"
done
