#!/usr/bin/env bash
#Display "Best School" 10 times, for the 9th iteration displays
#+Best School, then "Hi" on a new line.

i=1
while [ $i -le 10 ]
do
    echo "Best School"
    ((i++))
    if [ $i -eq 10 ]
    then
	echo "Hi"
    fi
done
