#!/usr/bin/env bash
#Bash script that loops 1 to 10 and,
#+Display "bad luck" for the 4th iteration.
#+Display "good luck" for the 8th iteration.
#+Display "Best School" for the other iterations.

i=1
while [ $i -le 10 ]
do
    ((i++))

    if [ $i -eq 5 ]
    then
        echo "bad luck"
    elif [ $i -eq 9 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
done
